In [1]:
import pandas as pd
import numpy as np


In [2]:
pd.options.display.float_format = '{:.2f}'.format

In [3]:
np.set_printoptions(precision=2)

In [10]:
x1 = np.random.rand(2,5)*10
x1

array([[1.5 , 4.89, 4.47, 9.62, 4.44],
       [6.32, 3.32, 4.44, 8.38, 6.5 ]])

In [11]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.1 , -0.3 , -0.27, -0.96, -0.48],
       [-0.97, -0.88, -0.3 , -0.95, -0.56]])

In [12]:
np.concatenate([x1,x2])

array([[ 1.5 ,  4.89,  4.47,  9.62,  4.44],
       [ 6.32,  3.32,  4.44,  8.38,  6.5 ],
       [-0.1 , -0.3 , -0.27, -0.96, -0.48],
       [-0.97, -0.88, -0.3 , -0.95, -0.56]])

In [13]:
np.concatenate([x1,x2]).shape

(4, 5)

In [14]:
np.concatenate([x1,x2],axis=1)

array([[ 1.5 ,  4.89,  4.47,  9.62,  4.44, -0.1 , -0.3 , -0.27, -0.96,
        -0.48],
       [ 6.32,  3.32,  4.44,  8.38,  6.5 , -0.97, -0.88, -0.3 , -0.95,
        -0.56]])

In [15]:
np.concatenate([x1,x2],axis=1).shape

(2, 10)

In [19]:
s1 = pd.Series(x1[0], index=['a','b','c','d','e'])
s1

a   1.50
b   4.89
c   4.47
d   9.62
e   4.44
dtype: float64

In [26]:
s2 = pd.Series(x1[0], index=['x','d','z','r','a'])
s2

x   1.50
d   4.89
z   4.47
r   9.62
a   4.44
dtype: float64

In [27]:
pd.concat([s1,s2])

a   1.50
b   4.89
c   4.47
d   9.62
e   4.44
x   1.50
d   4.89
z   4.47
r   9.62
a   4.44
dtype: float64

In [28]:
pd.concat([s1,s2], axis=1)

0    1
a 1.50 4.44
b 4.89  nan
c 4.47  nan
d 9.62 4.89
e 4.44  nan
x  nan 1.50
z  nan 4.47
r  nan 9.62

In [32]:
#si quiero borrar los indices
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0    1
0 1.50 1.50
1 4.89 4.89
2 4.47 4.47
3 9.62 9.62
4 4.44 4.44

In [35]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns=['a','b'])
df1

a    b
0 9.90 5.68
1 3.41 9.24
2 3.57 8.90

In [36]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns=['a','b'], index=[2,3,4])
df2

a     b
2 -0.70 -0.89
3 -0.81 -0.32
4 -0.89 -0.24

In [37]:
pd.concat([df1,df2])

a     b
0  9.90  5.68
1  3.41  9.24
2  3.57  8.90
2 -0.70 -0.89
3 -0.81 -0.32
4 -0.89 -0.24

In [38]:
pd.concat([df1,df2], axis=1)

a    b     a     b
0 9.90 5.68   nan   nan
1 3.41 9.24   nan   nan
2 3.57 8.90 -0.70 -0.89
3  nan  nan -0.81 -0.32
4  nan  nan -0.89 -0.24

In [39]:
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 3.57 8.90 -0.70 -0.89

In [40]:
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 9.90 5.68 -0.70 -0.89
1 3.41 9.24 -0.81 -0.32
2 3.57 8.90 -0.89 -0.24

In [41]:
df1.append(df2)

a     b
0  9.90  5.68
1  3.41  9.24
2  3.57  8.90
2 -0.70 -0.89
3 -0.81 -0.32
4 -0.89 -0.24

In [42]:
df1.T

0    1    2
a 9.90 3.41 3.57
b 5.68 9.24 8.90

In [44]:
df1.T.append(df2.T).T

a    b     a     b
0 9.90 5.68   nan   nan
1 3.41 9.24   nan   nan
2 3.57 8.90 -0.70 -0.89
3  nan  nan -0.81 -0.32
4  nan  nan -0.89 -0.24